version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    container_name: app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=drivermetedb
      - DB_USER=biadevsoft
      - DB_PASS=aqwzsx1928
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:alpine3.17
    volumes:
      - dev-db-data:/var/lib/postresql/data
    container_name: db
    environment:
      - POSTGRES_DB=drivermetedb
      - POSTGRES_USER=biadevsoft
      - POSTGRES_PASSWORD=aqwzsx1928

volumes:
  dev-db-data:
  dev-static-data: