version: "3.9"

services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis

  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - dev-db-data:/var/lib/postresql/data
    environment:
      - POSTGRES_DB=drivermetedb
      - POSTGRES_USER=biadevsoft
      - POSTGRES_PASSWORD=aqwzsx1928

  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command:
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=drivermetedb
      - DB_USER=biadevsoft
      - DB_PASS=aqwzsx1928
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    container_name: celery
    command: celery -A app worker -l INFO
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=drivermetedb
      - DB_USER=biadevsoft
      - DB_PASS=aqwzsx1928
    depends_on:
      - db
      - redis
      - app

volumes:
  dev-db-data:
  dev-static-data: