# Generated by Django 4.2 on 2023-04-11 01:35

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=50, null=True, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=17, null=True, unique=True, verbose_name='phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='gender')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('rider', 'Rider'), ('driver', 'Driver')], max_length=10, verbose_name='user type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('banned', 'Banned'), ('reject', 'Reject')], max_length=20, verbose_name='status')),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='fcm token')),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='remember token')),
                ('profile_image', models.ImageField(null=True, upload_to=core.models.image_file_path, verbose_name='profile image')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email verified at')),
                ('last_notification_seen', models.DateTimeField(blank=True, null=True, verbose_name='last notification seen')),
                ('is_online', models.BooleanField(default=False, verbose_name='is online')),
                ('is_available', models.BooleanField(default=False, verbose_name='is available')),
                ('is_verified_driver', models.BooleanField(default=False, verbose_name='verified driver')),
                ('login_type', models.CharField(choices=[('mobile', 'mobile'), ('email', 'Email'), ('facebook', 'Facebook'), ('google', 'Google'), ('twitter', 'Twitter')], default='email', max_length=20, verbose_name='login type')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('last_location_update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last location update')),
                ('fleet_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='fleet id')),
                ('player_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='player id')),
                ('service_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='service id')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('type', models.CharField(default='driver', max_length=30, verbose_name='type')),
                ('is_required', models.BooleanField(default=False, verbose_name='is required')),
                ('has_expiry_date', models.BooleanField(default=False, verbose_name='has expiry date')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('distance_unit', models.CharField(choices=[('km', 'Km'), ('mile', 'Mile')], default='km', max_length=5, verbose_name='distance unit')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='coordinates')),
                ('status', models.IntegerField(default=1, verbose_name='status')),
                ('timezone', models.CharField(default='UTC', max_length=30, verbose_name='timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'regions',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('guard_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='guard name')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'roles',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='total amount')),
                ('online_received', models.FloatField(blank=True, null=True, verbose_name='online received')),
                ('collected_cash', models.FloatField(blank=True, null=True, verbose_name='collected cash')),
                ('manual_received', models.FloatField(blank=True, null=True, verbose_name='manual received')),
                ('total_withdrawn', models.FloatField(blank=True, null=True, verbose_name='total withdrawn')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='car model')),
                ('car_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='car color')),
                ('car_plate_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='car plate number')),
                ('car_production_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='car production year')),
                ('work_address', models.TextField(blank=True, null=True, verbose_name='work address')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='home address')),
                ('work_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='work latitude')),
                ('work_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='work longitude')),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='home latitude')),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='home longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_userdetail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user detail',
                'verbose_name_plural': 'user details',
            },
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='bank name')),
                ('bank_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='bank code')),
                ('account_holder_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='account holder name')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='account number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_userbankaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user bank account',
                'verbose_name_plural': 'user bank accounts',
            },
        ),
        migrations.CreateModel(
            name='Sos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('contact_number', models.CharField(blank=True, max_length=17, null=True, verbose_name='contact number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=9, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_sos', to='core.regions')),
            ],
            options={
                'verbose_name': 'sos',
                'verbose_name_plural': 'sos',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('document_image', models.ImageField(null=True, upload_to=core.models.image_file_path, verbose_name='document image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_id_driverdocument', to='core.document')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_id_driverdocument', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'driver document',
                'verbose_name_plural': 'driver document',
            },
        ),
    ]
