# Generated by Django 4.1.7 on 2023-03-23 21:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_timezone_alter_wallet_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('guard_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='guard name')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'roles',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='remember_token',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=core.models.user_image_file_path),
        ),
    ]
