# Generated by Django 4.1.7 on 2023-03-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roles_remove_user_fcm_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_id',
            new_name='user',
        ),
    ]
